name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache YARN dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - run: yarn --no-progress --non-interactive --frozen-lockfile

      - run: yarn build
      - run: yarn test

  test-e2e:
    name: Unit Tests E2E
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 10.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache YARN dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - name: Install Dependencies
        run: yarn --no-progress --non-interactive --frozen-lockfile

      - run: yarn build
      - run: |
          git clone https://github.com/ethereum-optimism/optimism.git
          cd optimism
          git checkout ae1ac05d7032422a71caf25d16f6e548df5b8d7f
          cd ops
          export COMPOSE_DOCKER_CLI_BUILD=1
          export DOCKER_BUILDKIT=1
          docker-compose build
          docker-compose up&

          cd ../../
          ./.github/workflows/wait-for-it.sh -h localhost -p 8080 -t 120
          sleep 60 # we still need to wait for contracts to be deployed really
          yarn test-e2e
